<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>2bb6b8de-d6b0-4b4f-a76c-4293f5ccdb5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div[2]/div[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.User__UserLink-wy6in-0.jqijjA</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5c9034a9-3e76-473c-be3c-9379ecf4b9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>User__UserLink-wy6in-0 jqijjA</value>
      <webElementGuid>eba97e8d-8ef5-4966-b918-7e078ec81cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://account.prusa3d.com/o/authorize/?client_id=M8LpfPFdUlFWcOpLmEdEm7IXmDQfNqhkMqRUYOnv&amp;response_type=code&amp;scope=basic_info&amp;redirect_uri=https://www.prusa3d.com/login/&amp;cancel_uri=https://www.prusa3d.com/#_ga=2.163248442.721941045.1674059658-1053192588.1674059658</value>
      <webElementGuid>e448e054-5a9c-4f7f-a30d-6692dc772c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>c96c376c-fd08-4e0c-83c3-9dff25955c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;Fixed-sc-1sqbh78-0 InformationHeader__FixedStyle-sc-2kbj1-1 dsAqSJ Itntr&quot;]/div[@class=&quot;InformationHeader__GrayLine-sc-2kbj1-0 bUVNuw&quot;]/div[@class=&quot;InformationHeader__Inner-sc-2kbj1-2 gCKLRj&quot;]/div[@class=&quot;InformationHeader__Right-sc-2kbj1-3 jbzgsG&quot;]/div[@class=&quot;User-wy6in-2 dZJRqf&quot;]/a[@class=&quot;User__UserLink-wy6in-0 jqijjA&quot;]</value>
      <webElementGuid>88b86874-d55f-49e8-9bdc-fcd30494f99c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[2]/div[3]/a</value>
      <webElementGuid>d66d4c2d-95e0-4961-8430-e4bbd2a2d390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>b641c7c9-be37-43b3-a89c-2a76ce64f3f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Polski'])[1]/following::a[1]</value>
      <webElementGuid>bcb83526-3784-42af-9bda-9a4c8041e00c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Italiano'])[1]/following::a[1]</value>
      <webElementGuid>a3cb0bc3-0a8f-4501-80b3-94c4953062d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Materials'])[1]/preceding::a[3]</value>
      <webElementGuid>1547ae65-2522-4fde-9f64-8939720861c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parts &amp; Accessories'])[1]/preceding::a[3]</value>
      <webElementGuid>8958634f-ee60-40c6-a838-7dfcecba435e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>565f4d60-41f5-4ea9-a1a5-109a594b9a19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://account.prusa3d.com/o/authorize/?client_id=M8LpfPFdUlFWcOpLmEdEm7IXmDQfNqhkMqRUYOnv&amp;response_type=code&amp;scope=basic_info&amp;redirect_uri=https://www.prusa3d.com/login/&amp;cancel_uri=https://www.prusa3d.com/#_ga=2.163248442.721941045.1674059658-1053192588.1674059658')]</value>
      <webElementGuid>2f881c6d-5b11-4dd7-8798-6047573cb0c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>4a01771f-e36f-4fee-b8aa-a41623bec312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://account.prusa3d.com/o/authorize/?client_id=M8LpfPFdUlFWcOpLmEdEm7IXmDQfNqhkMqRUYOnv&amp;response_type=code&amp;scope=basic_info&amp;redirect_uri=https://www.prusa3d.com/login/&amp;cancel_uri=https://www.prusa3d.com/#_ga=2.163248442.721941045.1674059658-1053192588.1674059658' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>3ff0c2a4-7cb9-40d8-83cf-2e3047e78d8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
