<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_User</name>
   <tag></tag>
   <elementGuidId>3ab8c615-d034-4491-b972-569db7c4cb93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@alt='JayLee Fagen']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.Dropdown__Ul-s848p4-0.fbeCZq > li.Dropdown__Li-s848p4-1.bnUebo > button.StyledButton__StyledButtonComponent-sc-93aam1-1.dOjKeB.Dropdown__DropdownButton-s848p4-4.gpukyR</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a4d357da-7c9b-4472-87f2-a0d0665b8733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>60aec43b-bab5-43dd-85e4-1880cd72c397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>StyledButton__StyledButtonComponent-sc-93aam1-1 dOjKeB Dropdown__DropdownButton-s848p4-4 gpukyR</value>
      <webElementGuid>44582180-18d1-4d00-a952-a15e3c4bced9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kind</name>
      <type>Main</type>
      <value>background</value>
      <webElementGuid>1413687d-c884-4d39-bbef-003e23799fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>02cb0224-e4a8-454b-bd94-186a046f66bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;Fixed-sc-1sqbh78-0 InformationHeader__FixedStyle-sc-2kbj1-1 dsAqSJ Itntr&quot;]/div[@class=&quot;InformationHeader__GrayLine-sc-2kbj1-0 bUVNuw&quot;]/div[@class=&quot;InformationHeader__Inner-sc-2kbj1-2 gCKLRj&quot;]/div[@class=&quot;InformationHeader__Right-sc-2kbj1-3 jbzgsG&quot;]/div[@class=&quot;User-wy6in-2 dZJRqf&quot;]/div[@class=&quot;Dropdown__ListWrapper-s848p4-2 EeUTE&quot;]/ul[@class=&quot;Dropdown__Ul-s848p4-0 fbeCZq&quot;]/li[@class=&quot;Dropdown__Li-s848p4-1 bnUebo&quot;]/button[@class=&quot;StyledButton__StyledButtonComponent-sc-93aam1-1 dOjKeB Dropdown__DropdownButton-s848p4-4 gpukyR&quot;]</value>
      <webElementGuid>71c960fc-e03d-4317-a53a-dd4177a98c8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@alt='JayLee Fagen']</value>
      <webElementGuid>e869a548-692e-4efc-a18c-fbafa15cd4b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[2]/div[3]/div/ul/li[5]/button</value>
      <webElementGuid>753f4e40-ec19-48f6-88bd-23fbc83c4559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My courses'])[1]/following::button[1]</value>
      <webElementGuid>6ade1d09-f988-4f07-9b40-64a737165812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In-stock Alerts'])[1]/following::button[1]</value>
      <webElementGuid>5e43f32f-2aa7-4a53-9666-2ba23c66b89f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Materials'])[1]/preceding::button[1]</value>
      <webElementGuid>699fe0ed-f62e-42ff-8e5f-2203ffc581a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parts &amp; Accessories'])[1]/preceding::button[1]</value>
      <webElementGuid>f06f0d2b-ddae-4a18-81c2-79f5be60f19b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>a0b6678d-516f-4994-b9ee-838ad74f7343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li[5]/button</value>
      <webElementGuid>5e279ae9-94ee-494d-8a08-5b6415b4601c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>964276ec-718f-43cf-ae9c-b6f02106f0f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
