<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Logout</name>
   <tag></tag>
   <elementGuidId>57802b71-eb6a-46b4-aea3-750a229108f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.Dropdown__Ul-s848p4-0.fbeCZq > li.Dropdown__Li-s848p4-1.bnUebo > button.StyledButton__StyledButtonComponent-sc-93aam1-1.dOjKeB.Dropdown__DropdownButton-s848p4-4.gpukyR</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1707294d-0fd5-4d28-bd3f-ef543a78dd26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>82606a73-730c-42cb-bb4e-966a18ea0201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>StyledButton__StyledButtonComponent-sc-93aam1-1 dOjKeB Dropdown__DropdownButton-s848p4-4 gpukyR</value>
      <webElementGuid>162b402c-9e06-49a5-a1dd-5ebefbf25adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kind</name>
      <type>Main</type>
      <value>background</value>
      <webElementGuid>3b6722a7-8ec3-4f5b-b803-ddbf68afe2cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>576feaf8-4028-43c6-8956-3e3e4b6133a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;Fixed-sc-1sqbh78-0 InformationHeader__FixedStyle-sc-2kbj1-1 dsAqSJ Itntr&quot;]/div[@class=&quot;InformationHeader__GrayLine-sc-2kbj1-0 bUVNuw&quot;]/div[@class=&quot;InformationHeader__Inner-sc-2kbj1-2 gCKLRj&quot;]/div[@class=&quot;InformationHeader__Right-sc-2kbj1-3 jbzgsG&quot;]/div[@class=&quot;User-wy6in-2 dZJRqf&quot;]/div[@class=&quot;Dropdown__ListWrapper-s848p4-2 EeUTE&quot;]/ul[@class=&quot;Dropdown__Ul-s848p4-0 fbeCZq&quot;]/li[@class=&quot;Dropdown__Li-s848p4-1 bnUebo&quot;]/button[@class=&quot;StyledButton__StyledButtonComponent-sc-93aam1-1 dOjKeB Dropdown__DropdownButton-s848p4-4 gpukyR&quot;]</value>
      <webElementGuid>381cee21-9d0b-4f41-99ea-b5c5211c6e4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[8]</value>
      <webElementGuid>f6bc70ea-ab6d-4f1f-a503-08f634329ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[2]/div[3]/div/ul/li[5]/button</value>
      <webElementGuid>fd67c364-95ac-4ce6-9820-74d7f48decd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My courses'])[1]/following::button[1]</value>
      <webElementGuid>139ab9f0-af1e-4775-838f-a1f409c72c10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In-stock Alerts'])[1]/following::button[1]</value>
      <webElementGuid>f2a53b50-ac44-4de4-8afc-ba5d7d748037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Materials'])[1]/preceding::button[1]</value>
      <webElementGuid>aeee5123-8a0c-497b-98be-8fc3c6b672d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parts &amp; Accessories'])[1]/preceding::button[1]</value>
      <webElementGuid>c5ec1b7f-0b2d-493f-bb8b-c5acf0bfad80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>167903ee-eeeb-4ad1-9b9d-1b49751f5238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li[5]/button</value>
      <webElementGuid>60c7209a-f6f0-4477-934d-9612e07dd3de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>471617cd-2081-4687-8be3-8fa900562fac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
